### ISSUE TITLE
Error when activating movement detection

### ISSUE THREAD

**Issue by dplazaespi** [SimoneAvogadro/CloudEdge4Tasker#4]
I get and error when I press the "Play" button quickly when the application start. If I wait some seconds until I press play it works. When I use the plugging from MacroDroid if fails and I think that is also related to to this issue. I have two cameras configured and I get the same error with both.

11-22 12:54:41.823  6986  6986 W System.err: java.lang.IllegalArgumentException: Empty key
11-22 12:54:41.823  6986  6986 W System.err: 	at javax.crypto.spec.SecretKeySpec.<init>(SecretKeySpec.java:96)
11-22 12:54:41.823  6986  6986 W System.err: 	at com.meari.sdk.utils.HmacshaUtil.HmacSHA1Encrypt(HmacshaUtil.java:40)
11-22 12:54:41.823  6986  6986 W System.err: 	at com.meari.sdk.utils.SdkUtils.getSignature(SdkUtils.java:886)
11-22 12:54:41.823  6986  6986 W System.err: 	at com.meari.sdk.MeariIotManager.setDeviceConfig(MeariIotManager.java:436)
11-22 12:54:41.823  6986  6986 W System.err: 	at com.meari.sdk.MeariIotManager.setDeviceConfig(MeariIotManager.java:424)
11-22 12:54:41.823  6986  6986 W System.err: 	at com.meari.sdk.UserRequestManager.setPirDetEnable(UserRequestManager.java:8243)
11-22 12:54:41.824  6986  6986 W System.err: 	at com.meari.sdk.MeariUser.setPirDetectionEnable(MeariUser.java:3837)
11-22 12:54:41.824  6986  6986 W System.err: 	at online.avogadro.mearitaskerplugin.device.CamManager$2.doSomething(CamManager.java:73)
11-22 12:54:41.824  6986  6986 W System.err: 	at online.avogadro.mearitaskerplugin.device.CamManager.doSomethingOnAllCameras(CamManager.java:187)
11-22 12:54:41.824  6986  6986 W System.err: 	at online.avogadro.mearitaskerplugin.device.CamManager.-$$Nest$mdoSomethingOnAllCameras(Unknown Source:0)
11-22 12:54:41.824  6986  6986 W System.err: 	at online.avogadro.mearitaskerplugin.device.CamManager$6$1.onSuccess(CamManager.java:141)
11-22 12:54:41.824  6986  6986 W System.err: 	at com.meari.sdk.MeariUser$3.onSuccess(MeariUser.java:1574)
11-22 12:54:41.824  6986  6986 W System.err: 	at com.meari.sdk.UserRequestManager$7.accept(UserRequestManager.java:2329)
11-22 12:54:41.824  6986  6986 W System.err: 	at com.meari.sdk.UserRequestManager$7.accept(UserRequestManager.java:2322)
11-22 12:54:41.824  6986  6986 W System.err: 	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
11-22 12:54:41.824  6986  6986 W System.err: 	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onNext(ObservableSubscribeOn.java:58)
11-22 12:54:41.824  6986  6986 W System.err: 	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
11-22 12:54:41.824  6986  6986 W System.err: 	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
11-22 12:54:41.824  6986  6986 W System.err: 	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
11-22 12:54:41.824  6986  6986 W System.err: 	at android.os.Handler.handleCallback(Handler.java:959)
11-22 12:54:41.824  6986  6986 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:100)
11-22 12:54:41.824  6986  6986 W System.err: 	at android.os.Looper.loopOnce(Looper.java:232)
11-22 12:54:41.824  6986  6986 W System.err: 	at android.os.Looper.loop(Looper.java:317)
11-22 12:54:41.824  6986  6986 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:8705)
11-22 12:54:41.824  6986  6986 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
11-22 12:54:41.824  6986  6986 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
11-22 12:54:41.824  6986  6986 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)

**Comment by SimoneAvogadro** [comment]
Thanks a lot for the report and for finding how to reproduce it.
It seems to be an initialization issue, I'll work on it while implementing the new features (currently: force one/all the camera to start the alarm siren, in order to create a "distributed siren" which is not easy to take down)

**Comment by SimoneAvogadro** [comment]
I've introduced some safeguards and now this should be resolved: did you see this happen again with the latest betas?

**Comment by dplazaespi** [comment]
I have tested V_1.6.0-beta3 and I'm getting the same error. I have to wait several seconds before pressing Play in order to avoid the failure.

**Comment by SimoneAvogadro** [comment]
I took some time during summer and found a way to replicate the issue: 1.7.0-RC1 should fix the issue!
Basically now the top buttons are greyed-out until the app has completed its internals and is ready to execute!

**Comment by SimoneAvogadro** [comment]
Does V_1.9.0 fix the issue for you?
For most users this issue should be fixed

**Comment by SimoneAvogadro** [comment]
Since I'm not receiving any more reports I'll close this
